const placeholderDrawing = {
  version: "5.4.2",
  objects: [
    {
      type: "line",
      version: "5.4.2",
      originX: "center",
      originY: "center",
      left: 30.51,
      top: 383.1,
      width: 0,
      height: 0,
      fill: "#000000",
      stroke: "#000000",
      strokeWidth: 2,
      strokeDashArray: null,
      strokeLineCap: "butt",
      strokeDashOffset: 0,
      strokeLineJoin: "miter",
      strokeUniform: false,
      strokeMiterLimit: 4,
      scaleX: 1,
      scaleY: 1,
      angle: 0,
      flipX: false,
      flipY: false,
      opacity: 1,
      shadow: null,
      visible: true,
      backgroundColor: "",
      fillRule: "nonzero",
      paintFirst: "fill",
      globalCompositeOperation: "source-over",
      skewX: 0,
      skewY: 0,
      x1: 0,
      x2: 0,
      y1: 0,
      y2: 0,
    },
  ],
}

export default placeholderDrawing
